
// import "./globals.css"
import Navbar from "@/components/Navbar"
import "../../node_modules/bootstrap/dist/css/bootstrap.css";
// import "../../node_modules/bootstrap/dist/js/bootstrap.bundle.min.js";
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        {children}</body>
    </html>
  )
}
